### ISSUE TITLE
Slow, search doesnt work, pages dont load

### ISSUE THREAD

**Issue by MrEnigmaSr** [GuduleLapointe/w4os#77] opened 2024-08-09 00:12 UTC
Using the versions of php and wordpress suggested by the github.  I have all dependencies.  This version of the plugin slows wordpress to a dangerous crawl.  My console log is full of error messages that are along the lines of 'this timed out'.  
If I were to venture a guess I would say this is because this plugin utilizes php's 'file_get_contents' instead of opening a curl or stream in many of it's functions.
Removing this addon causes wordpress to return to normal, usable speeds.
Any advice would be appreciated.  I would like to use this in the future.

**Comment by GuduleLapointe** [comment] 2024-08-09 13:40
That's unfortunate. As this is not happening usually, I guess it could be caused by a particular setting, e.g. a wrong URL given somewhere. However there should be a way to make sure it doesn't try indefinitely and log an appropriate error instead.

Could you send me the complete error message? As you said, file_get_contents is used in a lot of functions, so it would be better to know where to start.

The choice of file_get_contents or curl is mostly the result of the helpers initially collected from different projects, but I remember having to switch from curl to file_get_contents at least in one of them because of... timing issues! But I will have a fresh look on this, to figure if it's still relevant.

Thanks for your feedback!

**Comment by GuduleLapointe** [comment] 2024-08-12 16:24
There is another issue related to site performance, it might or might not be related, could you check if it matches your problems? #80

**Comment by GuduleLapointe** [comment] 2024-12-04 02:50
I close the issue as I got no answer to my questions, but if you still experience problems, feel free to reopen it with more details.

**Closed by GuduleLapointe** 2024-12-04 02:50 UTC
Labels: bug
